//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, ChatId, Seconds, Story, StoryId};

impl_payload! {
    /// Reposts a story on behalf of a managed business account. Requires the _can_manage_stories_ business bot right. Returns [`Story`] on success.
    ///
    /// [`Story`]: crate::types::Story
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub RepostStory (RepostStorySetters) => Story {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Identifier of the chat that posted the story
            pub from_chat_id: ChatId [into],
            /// Identifier of the story to repost
            pub from_story_id: StoryId,
            /// Period after which the reposted story is moved to the archive, in seconds
            pub active_period: Seconds,
        }
        optional {
            /// Pass _true_ to keep the reposted story accessible after it expires
            pub post_to_chat_page: bool,
            /// Pass _true_ if the content of the reposted story must be protected from forwarding and screenshotting
            pub protect_content: bool,
        }
    }
}
