//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{MessageEntity, ParseMode, Recipient, ThreadId, True};

impl_payload! {
    /// Use this method to send a draft of a text message. Returns _true_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendMessageDraft (SendMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
            /// Unique identifier of the draft message
            pub draft_id: i32,
            /// Text of the message draft to be sent, 1-4096 characters after entities parsing
            pub text: String [into],
        }
        optional {
            /// Unique identifier for the target message thread (topic) of the forum; for forum supergroups only
            pub message_thread_id: ThreadId,
            /// Mode for parsing entities in the message text. See [formatting options] for more details.
            ///
            /// [formatting options]: https://core.telegram.org/bots/api#formatting-options
            pub parse_mode: ParseMode,
            /// List of special entities that appear in the message text, which can be specified instead of _parse_mode_
            pub entities: Vec<MessageEntity> [collect],
        }
    }
}
