//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Recipient, True, UserId};

impl_payload! {
    /// Use this method to set a tag for a regular member in a group or a supergroup. The bot must be an administrator in the chat for this to work and must have the _can_manage_tags_ administrator right. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetChatMemberTag (SetChatMemberTagSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup (in the format `@supergroupusername`)
            pub chat_id: Recipient [into],
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
        optional {
            /// New tag for the member; 0-16 characters, emoji are not allowed
            pub tag: String [into],
        }
    }
}
